Correct insert_before functionality for deferred nodes
Pylons/colander pull request #343
Opened 2020-11-15 18:31 UTC by CogsAndGears

After binding, deferred nodes currently are always appended to the end of the list of node children, and named according to their attribute name. This change sends those nodes through the same logic currently implemented in `_add_node_children` so that they can be ordered and named appropriately.

It does this by breaking out the logic inside the loop in `_add_node_children` into its own function -- `_add_node_child` -- to keep the rest of the logic as close to the original as possible, and allowing individual children to be added. If it is preferable to keep helper functions to a minimum, I could modify this to accomplish the same task using only `_add_node_children` and passing the deferred nodes in with a list.

This only allows node arguments such as `insert_before` to affect the ordering; deferred nodes that do not specify an ordering will still be added to the end of the list of children.

2020-11-15 22:50 UTC, stevepiercy commented
You can ignore the lint errors. We need to run Black's latest version on the code base in a separate PR.

2020-11-15 23:12 UTC, stevepiercy requested changes
Minor wording change for the CHANGES.rst.

2020-11-15 23:13 UTC, stevepiercy commented
@ CogsAndGears would you please also sign [CONTRIBUTORS.txt](https://github.com/Pylons/colander/blob/master/CONTRIBUTORS.txt) if you have not yet already done so, and push that commit to this PR? Thank you!

2020-11-15 23:15 UTC, stevepiercy commented
I also want a maintainer to review.

2020-11-15 23:58 UTC, CogsAndGears commented on CHANGES.rst
> +  new node correctly instead of always appending to the end of
Incorporated the suggested wording change and signed CONTRIBUTORS.txt in commit 4002042. Thank you!

2020-11-16 03:39 UTC, stevepiercy approved these changes
Thank you! I've requested a review from a maintainer for final approval.

2020-11-16 20:46 UTC, mmerickel approved these changes

2020-11-16 20:47 UTC, merged