Update Multiple inheritance in basics.rst
Pylons/colander pull request #362
Opened 2024-02-23 21:30 UTC by bcarmo-caio

```
$ python --version
Python 3.9.18

$ pip freeze | grep colander
colander==2.0
```

2024-02-23 21:57 UTC, bcarmo-caio commented
Or perhaps

```
class Three(Two, One):
```

was meant. And then the output matches.

2024-05-16 17:46 UTC, tseaver commented
After I get the CI unstuck, I'll look more closely at the output here.

2024-05-16 18:04 UTC, tseaver requested changes
Thanks very much for the patch!  I've fixed the CI issue already, so this one should be ready to merge once the note I suggested is added.

2024-05-16 18:04 UTC, tseaver commented on docs/basics.rst
I think we need to add an explanatory comment that the order of the children in the output is governed by Python's `__mro__`, e.g.
```suggestion

.. note::

   The order of the children in the output above might seem suprising:
   it is governed by how Python's multiple-inheritance works (the
   ``__mro__`` order).
```

2024-05-16 18:13 UTC, merged